### PR TITLE
added more compile handles for boost library in cmake

### PR DESCRIPTION
**Pull request by knmcguire**
To solve the boost library problems given in this issue: https://github.com/IMRCLab/crazyswarm2/issues/1

### CODE REVIEW

**Comment by whoenig** [comment]
How did you install boost in Windows? I would like to try to enable CI for Windows first, see it fail there, and see it fixed with the PR:-)

**Comment by knmcguire** [comment]
On the [boost website](https://www.boost.org/users/download/) directly, go to prebuild windows libraries and select the right binary. In my case with visual studio 2019 community, I needed to get the 'boost_1_74_0-msvc-14.2-64.exe' install. It was not signed so needed to click through some security steps. 

Perhaps you could get the boost program options library files and just copy them directly in the CI?

**Comment by whoenig** [comment]
FYI, CI is now enabled and also passes since your PR was applied!

**Comment by knmcguire** [comment]
nice! One of the few times I actually fix a CI build instead of breaking it 😃 Thanks for merging!

**Pull request merged**
